spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fourman-project
    username: fourman
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jwt:
    secret: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb"

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: fourman.project1.domain
  configuration:
    map-underscore-to-camel-case: true
