spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fourman-project
    username: fourman
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

